###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union, Literal

from . import types

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################


class DeDupeResult(BaseModel):
    
    
    merged_results: List[Optional[str]]

class DynamicGraph(BaseModel):
    
    
    nodes: List["SimpleNode"]
    relationships: List["SimpleRelationship"]

class Properties(BaseModel):
    
    
    description: Optional[str] = None

class Resume(BaseModel):
    
    
    name: Optional[str] = None
    email: Optional[str] = None
    experience: List[Optional[str]]
    skills: List[Optional[str]]

class SimpleNode(BaseModel):
    
    
    id: Optional[str] = None
    type: Optional[str] = None
    properties: Optional["Properties"] = None

class SimpleRelationship(BaseModel):
    
    
    source_node_id: Optional[str] = None
    source_node_type: Optional[str] = None
    target_node_id: Optional[str] = None
    target_node_type: Optional[str] = None
    type: Optional[str] = None
    properties: Optional["Properties"] = None
